### ISSUE TITLE
Issue _skin.class.php upon new installation on b2evo-6.8.10

### ISSUE THREAD

**Issue by Metztli** [b2evolution/ark_skin#2]
Niltze [Hello]!

Long time ago, left you a message at
http://skins.b2evolution.net/ark-blog-skin#more360571

Issue has not been resolved, even from git.

Parse error: syntax error, unexpected '=', expecting ')' in /path-to-b2evo-6.8.10/skins/ark_skin/_skin.class.php on line 628 

Thank you in advance for your attention (hopefully) this time.

Best Professional Regards.

**Comment by miloszivojinovic** [comment]
Hello @Metztli ! Thanks for your message. We appreciate your interest in this skin.

We have just released the newest version of Ark Skin `1.3.0`.
Official GitHub release: https://github.com/b2evolution/ark_skin/releases/tag/1.3.0 (zipped package included).
Official b2evolution release: http://skins.b2evolution.net/ark-blog-skin (zipped package included).

Let us know what you think! Your comments are very much appreciated.

Best Regards.

**Comment by Metztli** [comment]
Appreciate, @miloszivojinovic-

Notwithstanding, after uploading Ark Skin 1.3.0, error occurs 3 lines down:

Parse error: syntax error, unexpected '=', expecting ')' in /path-to-b2evo-6.8.10/skins/ark_skin/_skin.class.php on line 631

Notwithstanding, 
Similar to prior version, Ark Skin 1.3.0 installs if:

I modify /path-to-b2evo-6.8.10/php/skins/ark_skin/_skin.class.php
Ark Skin line
631: if( !empty( $header_height = $this->get_setting( 'header_height' ) ) )
to
if( $header_height = $this->get_setting( 'header_height' ) )

i.e., removing !empty( )
Test install:
http://b2evo-nepohualtzintzin.rhcloud.com/index.php/a/ark-skin-1-3-0

Thanks!

**Comment by miloszivojinovic** [comment]
Hi again @Metztli .

We branched-out a new stable version with your fix: https://github.com/b2evolution/ark_skin/tree/develop-1.3.1. Please check it out and confirm that everything is working properly now so that I can merge it and release a new version.

Thanks!

**Comment by Metztli** [comment]
Indeed, @miloszivojinovic-
Ark Skin 1.3.1 now works "out of the box".
Test install:
http://cohuatl-nepohualtzintzin.rhcloud.com/index.php/a/ark-skin-1-3-1

Thanks!
